image: "gcc"

build:
    stage: build
    # instead of calling g++ directly you can also use some build toolkit like make
    # install the necessary build tools when needed
    before_script:
        - apt update && apt -y install cmake make autoconf build-essential llvm
    script:
        - ./build.sh
    artifacts:
      paths:
        - tests/geotest
        # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
        # cache:
        #   paths:
        #     - "*.o"
  
# run tests using the binary built before
test:
    stage: test
    script:
      - cd build/tests
      - ./geotest
