image: "stelzo/cpp-cmake-ubuntu"

geolib:
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -D CMAKE_CXX_COMPILER=clang++ ..
    - make
    - make test